(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const L="sDWkN6pm2AwhXYN4z6b2LV2Cv7281iLQ",b=20;let h=1,a="",i="";function w(n,t){a=n,i=t,h=1}async function S(){var n;try{const t=new Date().toISOString(),e=new URLSearchParams({apikey:L,page:h-1,size:b,sort_by:"eventdate",order:"asc",eventdate_from:t});return a&&e.append("keyword",a),i&&e.append("countryCode",i),((n=(await(await fetch(`https://app.ticketmaster.com/discovery/v2/events.json?${e}`)).json())._embedded)==null?void 0:n.events)||[]}catch(t){return console.log(t),[]}}const E="/event-booster/assets/symbol-defs-d9832d8e.svg",y=document.querySelector(".events-list");function P(){y.innerHTML=""}function O(n=[]){return n.length?n.sort((e,o)=>o.width-e.width)[0].url:""}function $(n=[]){const t=n.map(e=>{var d,f,m,p;const o=(f=(d=e._embedded)==null?void 0:d.venues)==null?void 0:f[0],r=(o==null?void 0:o.name)||"Unknown venue",s=((m=o==null?void 0:o.city)==null?void 0:m.name)||"",c=((p=o==null?void 0:o.country)==null?void 0:p.name)||"",v=[r,s,c].filter(Boolean).join(", ");return`
      <li class="list-item">
        <img src="${O(e.images)}" alt="${e.name}" loading="lazy">
        <h3>${e.name}</h3>
        <p>${e.dates.start.localDate}</p>
        <p>
          <svg class="icon-location">
            <use href="${E}#location"></use>
          </svg>
          ${v}
        </p>
      </li>`}).join("");y.insertAdjacentHTML("beforeend",t)}const C=document.querySelector(".hero-search"),g=document.querySelector(".search-input input"),l=document.querySelector(".search-select select");function u(n="",t=""){w(n,t),P(),S().then(e=>{if(!e.length){alert("Нічого не знайдено");return}$(e)}).catch(e=>{console.log("Помилка при отриманні events:",e)})}u();C.addEventListener("submit",n=>{n.preventDefault();const t=g.value.trim(),e=l.value;if(!t&&!e){alert("будь ласка, введіть пошук або оберіть країну");return}u(t,e)});l.addEventListener("change",()=>{const n=g.value.trim(),t=l.value;!n&&!t||u(n,t)});
//# sourceMappingURL=commonHelpers.js.map
